name: Deploy to Cachix

on:
  push:
    branches: [ main ]
  schedule:
    # Rebuild weekly to keep cache fresh
    - cron: '0 2 * * 0'

jobs:
  cachix-deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v14
      with:
        name: shedali
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community

    - name: Build and push all outputs
      run: |
        # Build all packages and push to cache
        nix build -L
        nix build .#script -L
        
        # Build development shell dependencies
        nix develop --command echo "Dev shell built"
        
        # Push everything to Cachix
        nix path-info --all | cachix push shedali