name: Deploy to Cachix

on:
  # Only run on main branch after CI passes
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]
  
  # Manual trigger
  workflow_dispatch:
  
  # Keep cache fresh
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday

jobs:
  cachix-deploy:
    # Only run if CI succeeded or it's a scheduled/manual run
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Use faster Nix installer
    - uses: DeterminateSystems/nix-installer-action@v4
    
    - uses: DeterminateSystems/magic-nix-cache-action@v2

    # This job WRITES to cache
    - uses: cachix/cachix-action@v14
      with:
        name: shedali
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'  # Write access
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community

    - name: Build all outputs
      run: |
        echo "Building all outputs for ${{ matrix.os }}..."
        
        # Build all packages
        nix build -L --json | jq -r '.[].outputs | to_entries[].value' | cachix push shedali
        nix build .#react -L --json | jq -r '.[].outputs | to_entries[].value' | cachix push shedali
        nix build .#server -L --json | jq -r '.[].outputs | to_entries[].value' | cachix push shedali
        nix build .#script -L --json | jq -r '.[].outputs | to_entries[].value' | cachix push shedali
        
        # Build and cache development shell
        nix develop --profile dev-profile --command true
        cachix push shedali dev-profile
        
    - name: Push all store paths
      run: |
        # Push any additional store paths
        nix path-info --all | grep -v '.drv$' | cachix push shedali || true