name: Pages
on:
  push:
    branches: [main, master]
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: cachix/cachix-action@v14
      with:
        name: shedali
        skipPush: true
    - run: nix build && cp -r result/www dist
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist
    - uses: actions/deploy-pages@v4
      id: deployment